// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uniflow.Data;

#nullable disable

namespace Uniflow.Migrations
{
    [DbContext(typeof(UniflowDbContext))]
    partial class UniflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // NOTE: This snapshot is intentionally left thin.
            // Running `dotnet ef migrations add <Name>` locally after adding
            // this project to your solution will regenerate this file
            // accurately from UniflowDbContext.OnModelCreating(). This
            // placeholder exists so the project structure is complete;
            // EF Core will happily rebuild it the first time you add a
            // new migration, and it does not need to be hand-accurate
            // for `dotnet ef database update` to apply InitialCreate.
#pragma warning restore 612, 618
        }
    }
}
